apiVersion: v1
kind: Pod
metadata:
  name: pichugin-maksim-0303
  namespace: pichugin-maksim-0303
  labels:
    app: pichugin-maksim
spec:
  containers:
    - name: pichugin-maksim
      image: pichuginmaksim/db:latest
      env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: password
        - name: DB_NAME
          value: testdb
      command: ["/bin/sh", "-c", "until pg_isready -h $DB_HOST -p $DB_PORT; do echo waiting for db; sleep 2; done && mpirun --allow-run-as-root -np 2 ./mpi_program"]
      args: ["-np", "2", "./mpi_program"]
      ports:
        - containerPort: 8080 
      
    - name: postgres
      image: postgres:15
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: testdb
      ports:
        - containerPort: 5432
